/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:abec5914-36cb-477f-83f0-d85b189d04ad",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_s3nLQlqM3",
    "aws_user_pools_web_client_id": "1428p5t7rqg66bk3udborusejd",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://ox3rwstqbjcotp66fwkj367nuq.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "proxychatf2d762e9bc784204880374b0ca905be4120629-dev",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_mobile_analytics_app_id": "0433e75c5e7747c48f6ff8d28960c1c6",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
